[package]
name = "simple-blockchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "0.2.36"
bincode = "1.3.3"
serde = "1.0.123"
hex = "0.4.3"